/**
 * Autogenerated code by SdkModelGenerator.
 * Do not edit. Any modification on this file will be removed automatically after project build
 *
 */
package com.hotelbeds.hotelapimodel.auto.annotation.validators;

import java.time.LocalDate;

import javax.validation.ConstraintValidator;
import javax.validation.ConstraintValidatorContext;


import lombok.extern.slf4j.Slf4j;

@Slf4j
public class FutureForLocalDateValidator implements ConstraintValidator<FutureForLocalDate, LocalDate> {
    @Override
    public void initialize(FutureForLocalDate constraintAnnotation) {
        // empty method
    }

    @Override
    public boolean isValid(LocalDate date, ConstraintValidatorContext context) {
        boolean result = true;
        if (date == null) {
            result = true;
        } else if (date.isEqual(LocalDate.now())) {
            result = true;
        } else {
            result = date.isAfter(LocalDate.now());
        }
        if (!result) {
            log.info("Date is not valid, it is not in the future, date: " + date);
        }
        return result;
    }
}
