/**
 * Autogenerated code by SdkModelGenerator.
 * Do not edit. Any modification on this file will be removed automatically after project build
 *
 */
package com.hotelbeds.hotelapimodel.auto.annotation.validators;

import java.lang.annotation.Documented;
import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

import javax.validation.Constraint;


/**
 * 
 * @author
 *
 */
@Documented
@Retention(RetentionPolicy.RUNTIME)
@Target(ElementType.FIELD)
@Constraint(validatedBy = ValidLimitFilterValidator.class)
public @interface ValidLimitFilter {

    /**
     * 
     * @return
     */
    String message() default "";

    /**
     * 
     * @return
     */
    Class<?>[] groups() default {};

    /**
     * 
     * @return
     */
    Class<?>[] payload() default {};

}
