/**
 * Autogenerated code by SdkModelGenerator.
 * Do not edit. Any modification on this file will be removed automatically after project build
 *
 */
package com.hotelbeds.hotelapimodel.auto.annotation.validators;

import javax.validation.ConstraintValidator;
import javax.validation.ConstraintValidatorContext;

import com.hotelbeds.hotelapimodel.auto.messages.AvailabilityRQ;

import lombok.extern.slf4j.Slf4j;

@Slf4j
public class ValidAvailabilityValidator implements ConstraintValidator<ValidAvailability, AvailabilityRQ> {
    @Override
    public void initialize(final ValidAvailability constraintAnnotation) {
        // empty method
    }

    @Override
    public boolean isValid(final AvailabilityRQ availabilityRQ, final ConstraintValidatorContext context) {
        boolean result = true;
        context.disableDefaultConstraintViolation();
        result = validOnlyUniqueFilterDestinationOrGeolocationOrHotels(availabilityRQ, context);
        return result;
    }

    private boolean validOnlyUniqueFilterDestinationOrGeolocationOrHotels(final AvailabilityRQ availabilityRQ,
        final ConstraintValidatorContext context) {
        boolean result = true;
        int found = 0;
        if (availabilityRQ.getDestination() != null) {
            found = found + 1;
        }
        if (availabilityRQ.getGeolocation() != null) {
            found = found + 1;
        }
        if (availabilityRQ.getHotelsFilter() != null) {
            found = found + 1;
        }
        if (found == 0 || found > 1) {
            context
                .buildConstraintViolationWithTemplate(
                    "{com.hotelbeds.AvailabilityFilter."
                        + "validOnlyUniqueFilterDestinationOrGeolocationOrHotels.message}")
                .addConstraintViolation();
            result = false;
            log.info("The request must have unique filter. Options: Destination, Geolocation, Hotels, destination: +"
                + availabilityRQ.getDestination() + " , geolocation: " + availabilityRQ.getGeolocation() + " , hotelsFilter: "
                + availabilityRQ.getHotelsFilter());
        }
        return result;
    }
}
