/**
 * Autogenerated code by SdkModelGenerator.
 * Do not edit. Any modification on this file will be removed automatically after project build
 *
 */
package com.hotelbeds.hotelapimodel.auto.annotation.validators;

import java.util.List;

import javax.validation.ConstraintValidator;
import javax.validation.ConstraintValidatorContext;

import com.hotelbeds.hotelapimodel.auto.model.ReviewFilter;

import lombok.extern.slf4j.Slf4j;

@Slf4j
public class ValidReviewFilterValidator implements ConstraintValidator<ValidReviewFilter, List<ReviewFilter>> {
    private static final String MIN_RATE = " , minRate: ";

    @Override
    public void initialize(ValidReviewFilter constraintAnnotation) {
        // empty method
    }

    @Override
    public boolean isValid(List<ReviewFilter> value, ConstraintValidatorContext context) {
        context.disableDefaultConstraintViolation();
        boolean result = true;
        if (value != null) {
            for (ReviewFilter review : value) {
                if (review.getMaxRate() == null && review.getMinRate() == null) {
                    context.buildConstraintViolationWithTemplate("{com.hotelbeds.ReviewFilter.rates.null.message}").addConstraintViolation();
                    result = false;
                    log.info("MaxRate and MinRate can not be null at same time, maxRate: " + review.getMaxRate() + MIN_RATE + review.getMinRate());
                } else if (result && review.getMaxRate() != null && review.getMinRate() != null
                    && (review.getMaxRate().compareTo(review.getMinRate()) < 0)) {
                    context.buildConstraintViolationWithTemplate("{com.hotelbeds.ReviewFilter.rates.value.message}").addConstraintViolation();
                    result = false;
                    log.info("Wrong Rates value. MaxRate should be bigger or equals than MinRate, maxRate: " + review.getMaxRate() + MIN_RATE
                        + review.getMinRate());
                }
                if (review.getMinReviewCount() != null && review.getMinReviewCount() == 0) {
                    context.buildConstraintViolationWithTemplate("{com.hotelbeds.ReviewFilter.reviewCounts.zero.message}").addConstraintViolation();
                    result = false;
                    log.info("Wrong ReviewCounts value. MaxReviewCount and MinReviewCount can not have value 0 or empty, maxRate: "
                        + review.getMaxRate() + MIN_RATE + review.getMinRate());
                }
            }
        }
        return result;
    }
}
