/**
 * Autogenerated code by SdkModelGenerator.
 * Do not edit. Any modification on this file will be removed automatically after project build
 *
 */
package com.hotelbeds.hotelapimodel.auto.annotation.validators;

import javax.validation.ConstraintValidator;
import javax.validation.ConstraintValidatorContext;

import com.hotelbeds.hotelapimodel.auto.model.GeoLocation;

import lombok.extern.slf4j.Slf4j;

@Slf4j
public class ValidGeoLocationValidator implements ConstraintValidator<ValidGeoLocation, GeoLocation> {
    @Override
    public void initialize(ValidGeoLocation constraintAnnotation) {
        // empty method
    }

    @Override
    public boolean isValid(GeoLocation geoLocation, ConstraintValidatorContext context) {
        boolean result = false;
        if (geoLocation.getRadius() != null && geoLocation.getUnit() != null && geoLocation.getSecondaryLongitude() == null
            && geoLocation.getSecondaryLatitude() == null) {
            result = true;
        } else if (geoLocation.getSecondaryLongitude() != null && geoLocation.getSecondaryLatitude() != null && geoLocation.getRadius() == null
            && geoLocation.getUnit() == null) {
            result = true;
        }
        if (!result) {
            log.info("Some required value in geolocation are empty, geolocation: {}", geoLocation);
        }
        return result;
    }
}
