/**
 * Autogenerated code by SdkModelGenerator.
 * Do not edit. Any modification on this file will be removed automatically after project build
 *
 */
package com.hotelbeds.hotelapimodel.auto.annotation.validators;

import java.lang.annotation.Documented;
import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

import javax.validation.Constraint;
import javax.validation.Payload;
import javax.validation.constraints.NotNull;


/**
 * The Interface ValidOccupancies.
 *
 * @author
 */
@NotNull
@Retention(RetentionPolicy.RUNTIME)
@Target(ElementType.FIELD)
@Constraint(validatedBy = ValidOccupanciesValidator.class)
@Documented
public @interface ValidOccupancies {

    /**
     * 
     * @return
     */
    String message() default "";

    /**
     * 
     * @return
     */
    Class<?>[] groups() default {};

    /**
     * 
     * @return
     */
    Class<? extends Payload>[] payload() default {};

    /**
     * 
     * @return
     */
    int maxRooms();

}
