/**
 * Autogenerated code by SdkModelGenerator.
 * Do not edit. Any modification on this file will be removed automatically after project build
 *
 */
package com.hotelbeds.hotelapimodel.auto.annotation.validators;

import java.time.LocalDate;
import java.time.temporal.ChronoUnit;

import javax.validation.ConstraintValidator;
import javax.validation.ConstraintValidatorContext;

import com.hotelbeds.hotelapimodel.auto.model.Stay;

import lombok.extern.slf4j.Slf4j;

/**
 * The Class ValidStayValidator.
 */
@Slf4j
public class ValidStayValidator implements ConstraintValidator<ValidStay, Stay> {
    private long maxDaysRange;

    /*
     * (non-Javadoc)
     * 
     * @see javax.validation.ConstraintValidator#initialize(java.lang.annotation.Annotation)
     */
    @Override
    public void initialize(final ValidStay constraintAnnotation) {
        maxDaysRange = constraintAnnotation.maxDaysRange();
    }

    /*
     * (non-Javadoc)
     * 
     * @see javax.validation.ConstraintValidator#isValid(java.lang.Object, javax.validation.ConstraintValidatorContext)
     */
    @Override
    public boolean isValid(final Stay stay, final ConstraintValidatorContext context) {
        boolean result = true;
        if (stay != null && stay.getCheckIn() != null && stay.getCheckOut() != null) {
            context.disableDefaultConstraintViolation();
            if (stay.getCheckIn().isBefore(LocalDate.now().minusDays(2))) {
                context.buildConstraintViolationWithTemplate("{com.hotelbeds.Stay.dates.checkin.future.message}").addConstraintViolation();
                result = false;
                log.debug("property must be in the future {}", stay.getCheckIn());
            } else if (stay.getCheckIn().isEqual(stay.getCheckOut()) || stay.getCheckIn().isAfter(stay.getCheckOut())) {
                context.buildConstraintViolationWithTemplate("{com.hotelbeds.Stay.dates.before.message}").addConstraintViolation();
                result = false;
                log.debug("CheckIn must be prior to checkOut date, checkin: {} , checkout: {}", stay.getCheckIn(), stay.getCheckOut());
            } else if (!isValidDateRange(stay.getCheckIn(), stay.getCheckOut())) {
                context.buildConstraintViolationWithTemplate("{com.hotelbeds.Stay.dates.range.message}").addConstraintViolation();
                result = false;
                log.debug("The number of nights must be less than or equal to {}, checkin: {} , checkout: {}", new Object[] {
                        maxDaysRange,
                        stay.getCheckIn(),
                        stay.getCheckOut()
                });
            }
        }
        return result;
    }

    private boolean isValidDateRange(LocalDate checkIn, LocalDate checkOut) {
        final long days = ChronoUnit.DAYS.between(checkIn, checkOut);
        boolean result = true;
        if (Long.valueOf(days).compareTo(maxDaysRange) > 0) {
            result = false;
        }
        return result;
    }
}
