/**
 * Autogenerated code by SdkModelGenerator.
 * Do not edit. Any modification on this file will be removed automatically after project build
 *
 */
package com.hotelbeds.hotelapimodel.auto.annotation.validators;

import java.lang.annotation.Documented;
import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

import javax.validation.Constraint;


/**
 * The Interface ValidBookingListDates.
 *
 * @author
 */
@Target({
        ElementType.TYPE, ElementType.ANNOTATION_TYPE
})
@Retention(RetentionPolicy.RUNTIME)
@Constraint(validatedBy = {
        ValidBookingListDatesValidator.class
})
@Documented
public @interface ValidBookingListDates {

    /**
     * Message.
     *
     * @return the string
     */
    String message() default "";

    /**
     * Groups.
     *
     * @return the class[]
     */
    Class<?>[] groups() default {};

    /**
     * Payload.
     *
     * @return the class[]
     */
    Class<?>[] payload() default {};

    /**
     * Max days range.
     *
     * @return the long
     */
    long maxDaysRange();
}
