/**
 * Autogenerated code by SdkModelGenerator.
 * Do not edit. Any modification on this file will be removed automatically after project build
 *
 */
package com.hotelbeds.distribution.hotel_api_model.auto.annotation.validators;

/*
 * #%L
 * hotel-api-model
 * %%
 * Copyright (C) 2015 HOTELBEDS, S.L.U.
 * %%
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation, either version 2.1 of the
 * License, or (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Lesser Public License for more details.
 * 
 * You should have received a copy of the GNU General Lesser Public
 * License along with this program.  If not, see
 * <http://www.gnu.org/licenses/lgpl-2.1.html>.
 * #L%
 */


import javax.validation.ConstraintValidator;
import javax.validation.ConstraintValidatorContext;

import com.hotelbeds.distribution.hotel_api_model.auto.messages.BookingListRQ;

public class ValidBookingListPaginationValidator implements ConstraintValidator<ValidBookingListPagination, Object> {

    private long maxBookingsRange;

    @Override
    public void initialize(ValidBookingListPagination constraintAnnotation) {
        maxBookingsRange = constraintAnnotation.maxBookingsRange();
    }

    @Override
    public boolean isValid(Object value, ConstraintValidatorContext context) {
        if (!(value instanceof BookingListRQ)) {
            throw new IllegalArgumentException("Expected a parameter of type XMLBookingListRQ or JSONBookingListRQ");
        }
        Integer from = null;
        Integer to = null;
        if (value instanceof BookingListRQ) {
            from = ((BookingListRQ) value).getFrom();
            to = ((BookingListRQ) value).getTo();
        }
        context.disableDefaultConstraintViolation();
        if (from <= 0) {
            context.buildConstraintViolationWithTemplate(
                "{com.hotelbeds.distribution.hotel_api_webapp.webapp.internal.messages.BookingListRQ.pagination.minimun.message}")
                .addConstraintViolation();
            return false;
        } else if (from.compareTo(to) > 0) {
            context.buildConstraintViolationWithTemplate(
                "{com.hotelbeds.distribution.hotel_api_webapp.webapp.internal.messages.BookingListRQ.pagination.before.message}")
                .addConstraintViolation();
            return false;
        } else if (!isValidBookingsRange(from, to)) {
            context.buildConstraintViolationWithTemplate(
                "{com.hotelbeds.distribution.hotel_api_webapp.webapp.internal.messages.BookingListRQ.pagination.range.message}")
                .addConstraintViolation();
            return false;
        }
        return true;
    }

    private boolean isValidBookingsRange(Integer from, Integer to) {
        final long bookings = to - from + 1; //from and to are inclusive
        if (bookings > maxBookingsRange) {
            return false;
        }
        return true;
    }
}
