/**
 * Autogenerated code by SdkModelGenerator.
 * Do not edit. Any modification on this file will be removed automatically after project build
 *
 */
package com.hotelbeds.distribution.hotel_api_model.auto.annotation.validators;

/*
 * #%L
 * hotel-api-model
 * %%
 * Copyright (C) 2015 HOTELBEDS, S.L.U.
 * %%
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation, either version 2.1 of the
 * License, or (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Lesser Public License for more details.
 * 
 * You should have received a copy of the GNU General Lesser Public
 * License along with this program.  If not, see
 * <http://www.gnu.org/licenses/lgpl-2.1.html>.
 * #L%
 */


import javax.validation.ConstraintValidator;
import javax.validation.ConstraintValidatorContext;

import com.hotelbeds.distribution.hotel_api_model.auto.common.SimpleTypes;
import com.hotelbeds.distribution.hotel_api_model.auto.model.Filter;

public class ValidLimitFilterValidator implements ConstraintValidator<ValidLimitFilter, Filter> {

    @Override
    public void initialize(final ValidLimitFilter constraintAnnotation) {
        // TODO Auto-generated method stub
    }

    @Override
    public boolean isValid(final Filter limit, final ConstraintValidatorContext context) {
        if (limit != null) {
            if (limit.getMinRate() != null && limit.getMaxRate() != null && limit.getMinRate().compareTo(limit.getMaxRate()) > 0) {
                context.buildConstraintViolationWithTemplate(SimpleTypes.WRONG_LIMITS_PRICE_RANGE_MESSAGE).addConstraintViolation();
                return false;

            }
            if (limit.getMinCategory() != null && limit.getMaxCategory() != null) {
                if (limit.getMinCategory() > limit.getMaxCategory()) {
                    context.disableDefaultConstraintViolation();
                    context.buildConstraintViolationWithTemplate(SimpleTypes.WRONG_LIMITS_CATEGORY_RANGE_MESSAGE).addConstraintViolation();
                    return false;
                }
            }
        }
        return true;
    }
}
