/**
 * Autogenerated code by SdkModelGenerator.
 * Do not edit. Any modification on this file will be removed automatically after project build
 *
 */
package com.hotelbeds.hotelapimodel.auto.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.hotelbeds.hotelapimodel.auto.common.SimpleTypes.RateType;
import com.hotelbeds.hotelapimodel.auto.convert.json.RateSerializer;
import com.hotelbeds.hotelapimodel.auto.model.Cost;
import java.math.BigDecimal;
import javax.validation.Valid;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;

import lombok.ToString;
import lombok.NoArgsConstructor;
import lombok.Data;

@XmlAccessorType(XmlAccessType.FIELD)
@JsonInclude(Include.NON_NULL)
@ToString
@NoArgsConstructor
@Data
public class BasicRate {

	@JsonProperty
	@XmlAttribute
	private String rateKey;
	@XmlAttribute
	private String rateClass;
	@XmlAttribute
	@Valid
	private RateType rateType;
	@XmlAttribute
	@JsonSerialize(using = RateSerializer.class)
	private BigDecimal net;
	@XmlAttribute
	@JsonSerialize(using = RateSerializer.class)
	private BigDecimal discount;
	@XmlAttribute
	@JsonSerialize(using = RateSerializer.class)
	private BigDecimal discountPCT;
	@XmlAttribute
	@JsonSerialize(using = RateSerializer.class)
	private BigDecimal sellingRate;
	@XmlAttribute
	@JsonSerialize(using = RateSerializer.class)
	private BigDecimal hotelSellingRate;
	@XmlAttribute
	@JsonSerialize(using = RateSerializer.class)
	private BigDecimal amount;
	@XmlAttribute
	private String hotelCurrency;
	@XmlAttribute
	private Boolean hotelMandatory;
	@XmlAttribute
	private Integer allotment;
	@XmlAttribute
	@JsonSerialize(using = RateSerializer.class)
	private BigDecimal commission;
	@XmlAttribute
	@JsonSerialize(using = RateSerializer.class)
	private BigDecimal commissionVAT;
	@XmlAttribute
	@JsonSerialize(using = RateSerializer.class)
	private BigDecimal commissionPCT;
	@XmlElement
	private Cost cost;


}