/**
 * Autogenerated code by SdkModelGenerator.
 * Do not edit. Any modification on this file will be removed automatically after project build
 *
 */
package com.hotelbeds.hotelapimodel.auto.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.hotelbeds.hotelapimodel.auto.common.SimpleTypes.ShoppingCartStatus;
import com.hotelbeds.hotelapimodel.auto.convert.json.DateSerializer;
import com.hotelbeds.hotelapimodel.auto.convert.json.RateSerializer;
import com.hotelbeds.hotelapimodel.auto.model.Holder;
import com.hotelbeds.hotelapimodel.auto.model.Hotel;
import com.hotelbeds.hotelapimodel.auto.model.ModificationPolicies;
import java.math.BigDecimal;
import java.time.LocalDate;

import lombok.ToString;
import lombok.NoArgsConstructor;
import lombok.Data;

@JsonInclude(Include.NON_NULL)
@ToString
@NoArgsConstructor
@Data
public class Booking {

	private String reference;
	private String cancellationReference;
	private String clientReference;
	@JsonProperty
	@JsonSerialize(using = DateSerializer.class)
	private LocalDate creationDate;
	private ShoppingCartStatus status;
	private ModificationPolicies modificationPolicies;
	@JsonSerialize(using = RateSerializer.class)
	private BigDecimal agCommision;
	@JsonSerialize(using = RateSerializer.class)
	private BigDecimal commisionVAT;
	private String creationUser;
	private Holder holder;
	private Hotel hotel;
	private String remark;
	private BigDecimal totalSellingRate;
	private BigDecimal totalNet;
	private BigDecimal pendingAmount;
	private String currency;


}