/**
 * Autogenerated code by SdkModelGenerator.
 * Do not edit. Any modification on this file will be removed automatically after project build
 *
 */
package com.hotelbeds.hotelapimodel.auto.model;

import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import lombok.ToString;
import lombok.NoArgsConstructor;
import lombok.Data;

@ToString
@NoArgsConstructor
@Data
public class Card {

	@NotNull
	@Size(min = 1, max = 10, message = "{javax.validation.constraints.Size.message}") 
	private String type;
	@Size(min = 0, max = 25, message = "{javax.validation.constraints.Size.message}") 
	private String content;


}