/**
 * Autogenerated code by SdkModelGenerator.
 * Do not edit. Any modification on this file will be removed automatically after project build
 *
 */
package com.hotelbeds.hotelapimodel.auto.model;

import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;

import lombok.ToString;
import lombok.NoArgsConstructor;
import lombok.Data;

@XmlAccessorType(XmlAccessType.FIELD)
@ToString
@NoArgsConstructor
@Data
public class Card {

	@XmlAttribute
	@NotNull
	@Size(min = 1, max = 10, message = "{javax.validation.constraints.Size.message}") 
	private String type;
	@Size(min = 0, max = 25, message = "{javax.validation.constraints.Size.message}") 
	private String content;


}