/**
 * Autogenerated code by SdkModelGenerator.
 * Do not edit. Any modification on this file will be removed automatically after project build
 *
 */
package com.hotelbeds.hotelapimodel.auto.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.hotelbeds.hotelapimodel.auto.common.SimpleTypes.HotelPackage;
import com.hotelbeds.hotelapimodel.auto.common.SimpleTypes.ShowDirectPayment;
import com.hotelbeds.hotelapimodel.auto.convert.json.RateSerializer;
import java.math.BigDecimal;
import javax.validation.Valid;
import javax.validation.constraints.Min;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;

import lombok.ToString;
import lombok.NoArgsConstructor;
import lombok.Data;
import lombok.AllArgsConstructor;

@XmlAccessorType(XmlAccessType.FIELD)
@JsonInclude(Include.NON_NULL)
@ToString
@NoArgsConstructor
@Data
@AllArgsConstructor
public class Filter {

	@XmlAttribute
	@Min(value = 1)
	private Integer maxHotels;
	@XmlAttribute
	@Min(value = 1)
	private Integer maxRooms;
	@XmlAttribute
	@Min(value = 0)
	@JsonSerialize(using = RateSerializer.class)
	private BigDecimal minRate;
	@XmlAttribute
	@Min(value = 0)
	@JsonSerialize(using = RateSerializer.class)
	private BigDecimal maxRate;
	@XmlAttribute
	@Min(value = 1)
	private Integer maxRatesPerRoom;
	@XmlAttribute
	private Boolean packaging;
	@XmlAttribute
	@Valid
	private ShowDirectPayment paymentType;
	@XmlAttribute
	@Valid
	private HotelPackage hotelPackage;
	@XmlAttribute
	@Min(value = 1)
	private Integer minCategory;
	@XmlAttribute
	@Min(value = 1)
	private Integer maxCategory;
	@XmlAttribute
	private String contract;


}