/**
 * Autogenerated code by SdkModelGenerator.
 * Do not edit. Any modification on this file will be removed automatically after project build
 *
 */
package com.hotelbeds.hotelapimodel.auto.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.hotelbeds.hotelapimodel.auto.annotation.validators.ValidGeoLocation;
import com.hotelbeds.hotelapimodel.util.UnitMeasure;
import java.math.BigDecimal;
import javax.validation.constraints.NotNull;

import lombok.ToString;
import lombok.NoArgsConstructor;
import lombok.Data;

@JsonInclude(Include.NON_NULL)
@ValidGeoLocation
@ToString
@NoArgsConstructor
@Data
public class GeoLocation {

	@NotNull
	private BigDecimal longitude;
	@NotNull
	private BigDecimal latitude;
	private BigDecimal radius;
	private UnitMeasure unit;
	private BigDecimal secondaryLatitude;
	private BigDecimal secondaryLongitude;


}