/**
 * Autogenerated code by SdkModelGenerator.
 * Do not edit. Any modification on this file will be removed automatically after project build
 *
 */
package com.hotelbeds.hotelapimodel.auto.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.hotelbeds.hotelapimodel.auto.annotation.validators.ValidGeoLocation;
import com.hotelbeds.hotelapimodel.util.UnitMeasure;
import java.math.BigDecimal;
import javax.validation.constraints.NotNull;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;

import lombok.ToString;
import lombok.NoArgsConstructor;
import lombok.Data;

@XmlAccessorType(XmlAccessType.FIELD)
@JsonInclude(Include.NON_NULL)
@ValidGeoLocation
@ToString
@NoArgsConstructor
@Data
public class GeoLocation {

	@XmlAttribute
	@NotNull
	private BigDecimal longitude;
	@XmlAttribute
	@NotNull
	private BigDecimal latitude;
	@XmlAttribute
	private BigDecimal radius;
	@XmlAttribute
	private UnitMeasure unit;
	@XmlAttribute
	private BigDecimal secondaryLatitude;
	@XmlAttribute
	private BigDecimal secondaryLongitude;


}