/**
 * Autogenerated code by SdkModelGenerator.
 * Do not edit. Any modification on this file will be removed automatically after project build
 *
 */
package com.hotelbeds.hotelapimodel.auto.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import lombok.ToString;
import lombok.NoArgsConstructor;
import lombok.Data;

@JsonInclude(Include.NON_NULL)
@ToString
@NoArgsConstructor
@Data
public class Holder {

	@Size(min = 1, max = 50, message = "{javax.validation.constraints.Size.message}") 
	@NotNull
	private String name;
	@Size(min = 1, max = 50, message = "{javax.validation.constraints.Size.message}") 
	@NotNull
	private String surname;


}