/**
 * Autogenerated code by SdkModelGenerator.
 * Do not edit. Any modification on this file will be removed automatically after project build
 *
 */
package com.hotelbeds.hotelapimodel.auto.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.hotelbeds.hotelapimodel.auto.convert.json.DateSerializer;
import com.hotelbeds.hotelapimodel.auto.convert.json.RateSerializer;
import com.hotelbeds.hotelapimodel.auto.model.CreditCard;
import com.hotelbeds.hotelapimodel.auto.model.Keyword;
import com.hotelbeds.hotelapimodel.auto.model.Review;
import com.hotelbeds.hotelapimodel.auto.model.Room;
import com.hotelbeds.hotelapimodel.auto.model.Supplier;
import com.hotelbeds.hotelapimodel.auto.model.Upselling;
import java.lang.Short;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.List;

import lombok.ToString;
import lombok.NoArgsConstructor;
import lombok.Data;

@JsonInclude(Include.NON_NULL)
@ToString
@NoArgsConstructor
@Data
public class Hotel {

	@JsonProperty
	@JsonSerialize(using = DateSerializer.class)
	private LocalDate checkIn;
	@JsonProperty
	@JsonSerialize(using = DateSerializer.class)
	private LocalDate checkOut;
	private Integer code;
	private String name;
	private String categoryCode;
	private String categoryName;
	private String destinationCode;
	private String destinationName;
	private Short zoneCode;
	private String zoneName;
	private String latitude;
	private String longitude;
	private String giata;
	private List<Keyword> keywords;
	private List<Review> reviews;
	private List<Room> rooms;
	@JsonSerialize(using = RateSerializer.class)
	private BigDecimal minRate;
	@JsonSerialize(using = RateSerializer.class)
	private BigDecimal maxRate;
	@JsonSerialize(using = RateSerializer.class)
	private BigDecimal totalSellingRate;
	@JsonSerialize(using = RateSerializer.class)
	private BigDecimal totalNet;
	@JsonSerialize(using = RateSerializer.class)
	private BigDecimal pendingAmount;
	private String currency;
	private List<CreditCard> creditCards;
	private Supplier supplier;
	private String clientComments;
	private BigDecimal cancellationAmount;
	private Upselling upselling;


}