/**
 * Autogenerated code by SdkModelGenerator.
 * Do not edit. Any modification on this file will be removed automatically after project build
 *
 */
package com.hotelbeds.hotelapimodel.auto.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.hotelbeds.hotelapimodel.auto.common.SimpleTypes.HotelCodeType;
import java.util.List;
import javax.validation.constraints.Size;

import lombok.ToString;
import lombok.NoArgsConstructor;
import lombok.Data;
import lombok.AllArgsConstructor;

@JsonInclude(Include.NON_NULL)
@ToString
@NoArgsConstructor
@Data
@AllArgsConstructor
public class HotelsFilter {

	@JsonProperty("hotel")
	@Size(min = 0, max = 2000, message = "{javax.validation.constraints.Size.message}") 
	private List<Integer> hotels;
	private Boolean included;
	private HotelCodeType type;


}