/**
 * Autogenerated code by SdkModelGenerator.
 * Do not edit. Any modification on this file will be removed automatically after project build
 *
 */
package com.hotelbeds.hotelapimodel.auto.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.hotelbeds.hotelapimodel.auto.common.SimpleTypes.HotelbedsCustomerType;
import javax.validation.constraints.Min;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;

import lombok.ToString;
import lombok.NoArgsConstructor;
import lombok.Data;

@XmlAccessorType(XmlAccessType.FIELD)
@JsonInclude(Include.NON_NULL)
@ToString
@NoArgsConstructor
@Data
public class Pax {

	@XmlAttribute
	@Min(value = 1)
	private Integer roomId;
	@XmlAttribute
	@NotNull
	private HotelbedsCustomerType type;
	@XmlAttribute
	@Min(value = 0)
	private Integer age;
	@XmlAttribute
	@Size(min = 0, max = 50, message = "{javax.validation.constraints.Size.message}") 
	private String name;
	@XmlAttribute
	@Size(min = 0, max = 50, message = "{javax.validation.constraints.Size.message}") 
	private String surname;


}