/**
 * Autogenerated code by SdkModelGenerator.
 * Do not edit. Any modification on this file will be removed automatically after project build
 *
 */
package com.hotelbeds.hotelapimodel.auto.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.hotelbeds.hotelapimodel.auto.model.BillingAddress;
import com.hotelbeds.hotelapimodel.auto.model.BookingDevice;
import com.hotelbeds.hotelapimodel.auto.model.PaymentCard;
import com.hotelbeds.hotelapimodel.auto.model.PaymentContactData;
import javax.validation.constraints.NotNull;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;

import lombok.ToString;
import lombok.NoArgsConstructor;
import lombok.Data;

@XmlAccessorType(XmlAccessType.FIELD)
@JsonInclude(Include.NON_NULL)
@ToString
@NoArgsConstructor
@Data
public class PaymentData {

	@NotNull
	private PaymentCard paymentCard;
	@NotNull
	private PaymentContactData contactData;
	@XmlElement
	private BillingAddress billingAddress;
	@XmlElement
	private Integer webPartner;
	@XmlElement
	private BookingDevice device;


}