/**
 * Autogenerated code by SdkModelGenerator.
 * Do not edit. Any modification on this file will be removed automatically after project build
 *
 */
package com.hotelbeds.hotelapimodel.auto.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.hotelbeds.hotelapimodel.auto.common.SimpleTypes.PaymentType;
import com.hotelbeds.hotelapimodel.auto.convert.json.RateSerializer;
import com.hotelbeds.hotelapimodel.auto.model.CancellationPolicy;
import com.hotelbeds.hotelapimodel.auto.model.DailyRate;
import com.hotelbeds.hotelapimodel.auto.model.Offer;
import com.hotelbeds.hotelapimodel.auto.model.Promotion;
import com.hotelbeds.hotelapimodel.auto.model.ShiftRate;
import com.hotelbeds.hotelapimodel.auto.model.Taxes;
import com.hotelbeds.hotelapimodel.auto.model.VoucherComment;
import java.math.BigDecimal;
import java.util.List;
import javax.validation.Valid;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementWrapper;

import lombok.ToString;
import lombok.NoArgsConstructor;
import lombok.Data;
import lombok.EqualsAndHashCode;

@XmlAccessorType(XmlAccessType.FIELD)
@JsonInclude(Include.NON_NULL)
@ToString
@NoArgsConstructor
@Data
@EqualsAndHashCode(callSuper=false)
public class Rate extends BasicRate {

	@XmlAttribute
	private String rateCommentsId;
	@XmlAttribute
	private String rateComments;
	@XmlElementWrapper(name = "voucherComments")
	@XmlElement(name = "comment")
	private List<VoucherComment> voucherComments;
	@XmlAttribute
	private PaymentType paymentType;
	@XmlAttribute
	private Boolean packaging;
	@XmlAttribute
	private String boardCode;
	@XmlAttribute
	private String boardName;
	@XmlElementWrapper(name = "cancellationPolicies")
	@XmlElement(name = "cancellationPolicy")
	private List<CancellationPolicy> cancellationPolicies;
	@XmlElement(name = "taxes")
	private Taxes taxes;
	@XmlElement
	private RateBreakDown rateBreakDown;
	@XmlAttribute
	private Integer rooms;
	@XmlAttribute
	private Integer adults;
	@XmlAttribute
	private Integer children;
	@XmlAttribute
	private String childrenAges;
	@XmlElementWrapper(name = "promotions")
	@XmlElement(name = "promotion")
	private List<Promotion> promotions;
	@XmlElementWrapper(name = "offers")
	@XmlElement(name = "offer")
	private List<Offer> offers;
	@XmlElementWrapper(name = "shifts")
	@XmlElement(name = "shiftRate")
	@Valid
	private List<ShiftRate> shiftRates;
	@XmlAttribute
	@JsonSerialize(using = RateSerializer.class)
	private BigDecimal rateup;
	@XmlElementWrapper(name = "dailyRates")
	@XmlElement(name = "dailyRate")
	private List<DailyRate> dailyRates;


}