/**
 * Autogenerated code by SdkModelGenerator.
 * Do not edit. Any modification on this file will be removed automatically after project build
 *
 */
package com.hotelbeds.hotelapimodel.auto.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.hotelbeds.hotelapimodel.auto.model.RateDiscount;
import com.hotelbeds.hotelapimodel.auto.model.RateSupplement;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementWrapper;

import lombok.ToString;
import lombok.NoArgsConstructor;
import lombok.Data;

@XmlAccessorType(XmlAccessType.FIELD)
@JsonInclude(Include.NON_NULL)
@ToString
@NoArgsConstructor
@Data
public class RateBreakDown {

	@XmlElementWrapper(name = "rateDiscounts")
	@XmlElement(name = "rateDiscount")
	private List<RateDiscount> rateDiscounts;
	@XmlElementWrapper(name = "rateSupplements")
	@XmlElement(name = "rateSupplement")
	private List<RateSupplement> rateSupplements;


}