/**
 * Autogenerated code by SdkModelGenerator.
 * Do not edit. Any modification on this file will be removed automatically after project build
 *
 */
package com.hotelbeds.hotelapimodel.auto.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.hotelbeds.hotelapimodel.auto.common.SimpleTypes.PaymentType;
import com.hotelbeds.hotelapimodel.auto.convert.json.RateSerializer;
import com.hotelbeds.hotelapimodel.auto.model.CancellationPolicy;
import com.hotelbeds.hotelapimodel.auto.model.DailyRate;
import com.hotelbeds.hotelapimodel.auto.model.Offer;
import com.hotelbeds.hotelapimodel.auto.model.Promotion;
import com.hotelbeds.hotelapimodel.auto.model.ShiftRate;
import com.hotelbeds.hotelapimodel.auto.model.Taxes;
import java.math.BigDecimal;
import java.util.List;
import javax.validation.Valid;

import lombok.ToString;
import lombok.NoArgsConstructor;
import lombok.Data;
import lombok.EqualsAndHashCode;

@JsonInclude(Include.NON_NULL)
@ToString
@NoArgsConstructor
@Data
@EqualsAndHashCode(callSuper=false)
public class Rate extends BasicRate {

	private String rateCommentsId;
	private String rateComments;
	private PaymentType paymentType;
	private Boolean packaging;
	private String boardCode;
	private String boardName;
	private List<CancellationPolicy> cancellationPolicies;
	private Taxes taxes;
	private RateBreakDown rateBreakDown;
	private Integer rooms;
	private Integer adults;
	private Integer children;
	private String childrenAges;
	private List<Promotion> promotions;
	private List<Offer> offers;
	@Valid
	private List<ShiftRate> shiftRates;
	@JsonSerialize(using = RateSerializer.class)
	private BigDecimal rateup;
	private List<DailyRate> dailyRates;


}