/**
 * Autogenerated code by SdkModelGenerator.
 * Do not edit. Any modification on this file will be removed automatically after project build
 *
 */
package com.hotelbeds.hotelapimodel.auto.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.hotelbeds.hotelapimodel.auto.common.SimpleTypes.ReviewsType;
import java.math.BigDecimal;
import javax.validation.constraints.Digits;
import javax.validation.constraints.Min;
import javax.validation.constraints.NotNull;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;

import lombok.ToString;
import lombok.NoArgsConstructor;
import lombok.Data;

@XmlAccessorType(XmlAccessType.FIELD)
@JsonInclude(Include.NON_NULL)
@ToString
@NoArgsConstructor
@Data
public class ReviewFilter {

	@NotNull
	@XmlAttribute
	private ReviewsType type;
	@XmlAttribute
	@Min(value = 0)
	@Digits(fraction = 1, integer = 1)
	private BigDecimal minRate;
	@XmlAttribute
	@Min(value = 0)
	@Digits(fraction = 1, integer = 1)
	private BigDecimal maxRate;
	@XmlAttribute
	private Integer minReviewCount;


}