/**
 * Autogenerated code by SdkModelGenerator.
 * Do not edit. Any modification on this file will be removed automatically after project build
 *
 */
package com.hotelbeds.hotelapimodel.auto.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.hotelbeds.hotelapimodel.auto.common.SimpleTypes.ChannelType;
import com.hotelbeds.hotelapimodel.auto.common.SimpleTypes.DeviceType;
import javax.validation.Valid;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import lombok.ToString;
import lombok.NoArgsConstructor;
import lombok.Data;

@JsonInclude(Include.NON_NULL)
@ToString
@NoArgsConstructor
@Data
public class Source {

	@NotNull
	@Valid
	private ChannelType channel;
	@NotNull
	@Valid
	private DeviceType device;
	@Size(min = 0, max = 200, message = "{javax.validation.constraints.Size.message}") 
	private String deviceInfo;


}