/**
 * Autogenerated code by SdkModelGenerator.
 * Do not edit. Any modification on this file will be removed automatically after project build
 *
 */
package com.hotelbeds.hotelapimodel.auto.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.hotelbeds.hotelapimodel.auto.convert.json.DateSerializer;
import java.time.LocalDate;
import javax.validation.constraints.Min;
import javax.validation.constraints.NotNull;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

import com.hotelbeds.hotelapimodel.auto.convert.xml.LocalDateAdapter;
import lombok.ToString;
import lombok.NoArgsConstructor;
import lombok.Data;
import lombok.AllArgsConstructor;

@XmlAccessorType(XmlAccessType.FIELD)
@JsonInclude(Include.NON_NULL)
@ToString
@NoArgsConstructor
@Data
@AllArgsConstructor
public class Stay {

	@XmlAttribute
	@JsonProperty
	@JsonSerialize(using = DateSerializer.class)
	@XmlJavaTypeAdapter(value = LocalDateAdapter.class)
	@NotNull
	private LocalDate checkIn;
	@XmlAttribute
	@JsonProperty
	@JsonSerialize(using = DateSerializer.class)
	@XmlJavaTypeAdapter(value = LocalDateAdapter.class)
	@NotNull
	private LocalDate checkOut;
	@XmlAttribute
	@Min(value = 1)
	private Integer shiftDays;
	@XmlAttribute
	private Boolean allowOnlyShift;


}