/**
 * Autogenerated code by SdkModelGenerator.
 * Do not edit. Any modification on this file will be removed automatically after project build
 *
 */
package com.hotelbeds.hotelapimodel.auto.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.hotelbeds.hotelapimodel.auto.common.SimpleTypes.TaxType;
import com.hotelbeds.hotelapimodel.auto.convert.json.RateSerializer;
import java.math.BigDecimal;

import lombok.ToString;
import lombok.NoArgsConstructor;
import lombok.Data;

@JsonInclude(Include.NON_NULL)
@ToString
@NoArgsConstructor
@Data
public class Tax {

	private Boolean included;
	@JsonSerialize(using = RateSerializer.class)
	private BigDecimal percent;
	@JsonSerialize(using = RateSerializer.class)
	private BigDecimal amount;
	private String currency;
	private TaxType type;
	@JsonSerialize(using = RateSerializer.class)
	private BigDecimal clientAmount;
	private String clientCurrency;


}