/**
 * Autogenerated code by SdkModelGenerator.
 * Do not edit. Any modification on this file will be removed automatically after project build
 *
 */
package com.hotelbeds.hotelapimodel.auto.model;

import com.hotelbeds.hotelapimodel.auto.model.Tax;
import java.util.List;

import lombok.ToString;
import lombok.NoArgsConstructor;
import lombok.Data;

@ToString
@NoArgsConstructor
@Data
public class Taxes {

	private List<Tax> taxes;
	private Boolean allIncluded;


}