/**
 * Autogenerated code by SdkModelGenerator.
 * Do not edit. Any modification on this file will be removed automatically after project build
 *
 */
package com.hotelbeds.hotelapimodel.auto.messages;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.hotelbeds.hotelapimodel.auto.annotation.validators.ValidLimitFilter;
import com.hotelbeds.hotelapimodel.auto.annotation.validators.ValidOccupancies;
import com.hotelbeds.hotelapimodel.auto.annotation.validators.ValidReviewFilter;
import com.hotelbeds.hotelapimodel.auto.annotation.validators.ValidStay;
import com.hotelbeds.hotelapimodel.auto.common.SimpleTypes.Accommodation;
import com.hotelbeds.hotelapimodel.auto.model.Boards;
import com.hotelbeds.hotelapimodel.auto.model.Destination;
import com.hotelbeds.hotelapimodel.auto.model.Filter;
import com.hotelbeds.hotelapimodel.auto.model.GeoLocation;
import com.hotelbeds.hotelapimodel.auto.model.HotelsFilter;
import com.hotelbeds.hotelapimodel.auto.model.KeywordsFilter;
import com.hotelbeds.hotelapimodel.auto.model.Occupancy;
import com.hotelbeds.hotelapimodel.auto.model.ReviewFilter;
import com.hotelbeds.hotelapimodel.auto.model.Rooms;
import com.hotelbeds.hotelapimodel.auto.model.Source;
import com.hotelbeds.hotelapimodel.auto.model.Stay;
import java.util.List;
import javax.validation.Valid;
import javax.validation.constraints.NotNull;

import lombok.ToString;
import lombok.NoArgsConstructor;
import lombok.Data;
import lombok.EqualsAndHashCode;

@JsonInclude(Include.NON_NULL)
@ToString
@NoArgsConstructor
@Data
@EqualsAndHashCode(callSuper=false)
public class AvailabilityRQ extends AbstractGenericRequest {

	@NotNull
	@Valid
	@ValidStay(maxDaysRange = 30)
	private Stay stay;
	@Valid
	@ValidOccupancies(maxRooms = 5)
	private List<Occupancy> occupancies;
	@Valid
	private GeoLocation geolocation;
	@Valid
	private Destination destination;
	@JsonProperty("keywords")
	@Valid
	private KeywordsFilter keywordsFilter;
	@JsonProperty("hotels")
	@Valid
	private HotelsFilter hotelsFilter;
	@JsonProperty("reviews")
	@Valid
	@ValidReviewFilter
	private List<ReviewFilter> reviewsFilter;
	@Valid
	@ValidLimitFilter
	private Filter filter;
	@Valid
	private Boards boards;
	@Valid
	private Rooms rooms;
	private Boolean dailyRate;
	private String sourceMarket;
	@Valid
	private List<Accommodation> accommodations;
	@Valid
	private Source source;


}