/**
 * Autogenerated code by SdkModelGenerator.
 * Do not edit. Any modification on this file will be removed automatically after project build
 *
 */
package com.hotelbeds.hotelapimodel.auto.messages;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.hotelbeds.hotelapimodel.auto.common.SimpleTypes.BookingListFilterType;
import com.hotelbeds.hotelapimodel.auto.convert.json.DateSerializer;
import java.time.LocalDate;
import javax.validation.constraints.NotNull;

import lombok.ToString;
import lombok.NoArgsConstructor;
import lombok.Data;
import lombok.EqualsAndHashCode;

@JsonInclude(Include.NON_NULL)
@ToString
@NoArgsConstructor
@Data
@EqualsAndHashCode(callSuper=false)
public class BookingListRQ extends AbstractGenericRequest {

	@JsonProperty
	@JsonSerialize(using = DateSerializer.class)
	@NotNull
	private LocalDate start;
	@JsonProperty
	@JsonSerialize(using = DateSerializer.class)
	@NotNull
	private LocalDate end;
	@NotNull
	private Integer from;
	@NotNull
	private Integer to;
	@NotNull
	private Boolean includeCancelled;
	@NotNull
	private BookingListFilterType filterType;


}