/**
 * Autogenerated code by SdkModelGenerator.
 * Do not edit. Any modification on this file will be removed automatically after project build
 *
 */
package com.hotelbeds.hotelapimodel.auto.messages;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.hotelbeds.hotelapimodel.auto.model.BookingRoom;
import com.hotelbeds.hotelapimodel.auto.model.Holder;
import com.hotelbeds.hotelapimodel.auto.model.PaymentData;
import com.hotelbeds.hotelapimodel.auto.model.Voucher;
import java.util.List;
import javax.validation.Valid;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementWrapper;
import javax.xml.bind.annotation.XmlRootElement;

import lombok.ToString;
import lombok.NoArgsConstructor;
import lombok.Data;
import lombok.EqualsAndHashCode;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlRootElement(name = "bookingRQ", namespace = "http://www.hotelbeds.com/schemas/messages")
@JsonInclude(Include.NON_NULL)
@ToString
@NoArgsConstructor
@Data
@EqualsAndHashCode(callSuper=false)
public class BookingRQ extends AbstractGenericRequest {

	@XmlElement
	@NotNull
	@Valid
	private Holder holder;
	@XmlElementWrapper(name = "rooms")
	@XmlElement(name = "room")
	@NotNull
	@Size(min = 1, max = 2147483647, message = "{javax.validation.constraints.Size.message}") 
	@Valid
	private List<BookingRoom> rooms;
	@Valid
	private PaymentData paymentData;
	@NotNull
	@Size(min = 1, max = 20, message = "{javax.validation.constraints.Size.message}") 
	private String clientReference;
	@XmlElement
	@Size(min = 0, max = 2000, message = "{javax.validation.constraints.Size.message}") 
	private String remark;
	private Voucher voucher;


}