/**
 * Autogenerated code by SdkModelGenerator.
 * Do not edit. Any modification on this file will be removed automatically after project build
 *
 */
package com.hotelbeds.hotelapimodel.auto.messages;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.hotelbeds.hotelapimodel.auto.common.SimpleTypes.ChangeMode;
import com.hotelbeds.hotelapimodel.auto.model.Booking;
import javax.validation.Valid;
import javax.validation.constraints.NotNull;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;

import lombok.ToString;
import lombok.NoArgsConstructor;
import lombok.Data;
import lombok.EqualsAndHashCode;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlRootElement(name = "bookingChangeRQ", namespace = "http://www.hotelbeds.com/schemas/messages")
@JsonInclude(Include.NON_NULL)
@ToString
@NoArgsConstructor
@Data
@EqualsAndHashCode(callSuper=false)
public class BookingChangeRQ extends AbstractGenericRequest {

	@XmlAttribute
	@NotNull
	private String bookingId;
	@XmlElement
	@Valid
	@NotNull
	private ChangeMode mode;
	@XmlElement(name = "booking")
	@Valid
	@NotNull
	private Booking booking;


}