/**
 * Autogenerated code by SdkModelGenerator.
 * Do not edit. Any modification on this file will be removed automatically after project build
 *
 */
package com.hotelbeds.hotelapimodel.auto.messages;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.hotelbeds.hotelapimodel.auto.messages.HotelbedsError;
import com.hotelbeds.hotelapimodel.auto.model.AuditData;
import javax.validation.constraints.NotNull;

import lombok.ToString;
import lombok.NoArgsConstructor;
import lombok.Data;

@JsonInclude(Include.NON_NULL)
@ToString
@NoArgsConstructor
@Data
public class GenericResponse {

	private String echoToken;
	@NotNull
	private AuditData auditData;
	private HotelbedsError error;
	private String lsection;


}