/**
 * Autogenerated code by SdkModelGenerator.
 * Do not edit. Any modification on this file will be removed automatically after project build
 *
 */
package com.hotelbeds.hotelcontentapi.auto.messages;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import java.time.LocalDate;
import java.util.List;
import javax.validation.constraints.NotNull;

import lombok.ToString;
import lombok.NoArgsConstructor;
import lombok.Data;

@JsonInclude(Include.NON_NULL)
@ToString
@NoArgsConstructor
@Data
public abstract class AbstractGenericContentRequest {

	@NotNull
	private String language;
	@NotNull
	private Integer from;
	@NotNull
	private Integer to;
	private LocalDate lastUpdateTime;
	private List<String> ids;
	private String[] fields;
	private boolean useSecondaryLanguage;
	private String secondaryLanguage;


}