/**
 * Autogenerated code by SdkModelGenerator.
 * Do not edit. Any modification on this file will be removed automatically after project build
 *
 */
package com.hotelbeds.hotelcontentapi.auto.messages;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.hotelbeds.hotelcontentapi.auto.messages.AuditData;
import com.hotelbeds.hotelcontentapi.auto.messages.HotelbedsError;
import javax.validation.constraints.NotNull;

import lombok.ToString;
import lombok.NoArgsConstructor;
import lombok.Data;

@JsonInclude(Include.NON_NULL)
@ToString
@NoArgsConstructor
@Data
public abstract class AbstractGenericContentResponse {

	private Integer from;
	private Integer to;
	private Integer total;
	@NotNull
	private AuditData auditData;
	private HotelbedsError error;


}