/**
 * Autogenerated code by SdkModelGenerator.
 * Do not edit. Any modification on this file will be removed automatically after project build
 *
 */
package com.hotelbeds.hotelcontentapi.auto.messages;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonProperty;

import lombok.ToString;
import lombok.NoArgsConstructor;
import lombok.Data;

@JsonInclude(Include.NON_NULL)
@ToString
@NoArgsConstructor
@Data
public class FacilityType {

	private Integer code;
	@JsonProperty("textFlag")
	private Boolean conceptFlag;
	private Boolean numberFlag;
	private Boolean logicFlag;
	private Boolean feeFlag;
	private Boolean distanceFlag;
	private Boolean ageFromFlag;
	private Boolean ageToFlag;
	private Boolean dateFromFlag;
	private Boolean dateToFlag;
	private Boolean timeFromFlag;
	private Boolean timeToFlag;
	private Boolean indYesOrNoFlag;
	private Boolean amountFlag;
	private Boolean currencyFlag;
	private Boolean appTypeFlag;


}