/**
 * Autogenerated code by SdkModelGenerator.
 * Do not edit. Any modification on this file will be removed automatically after project build
 *
 */
package com.hotelbeds.hotelcontentapi.auto.messages;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.hotelbeds.hotelcontentapi.auto.messages.FreeTextSearchElement;
import java.util.List;

import lombok.ToString;
import lombok.NoArgsConstructor;
import lombok.Data;
import lombok.EqualsAndHashCode;

@JsonInclude(Include.NON_NULL)
@ToString
@NoArgsConstructor
@Data
@EqualsAndHashCode(callSuper=false)
public class FreeTextSearchRS2 extends AbstractGenericContentResponse {

	private boolean fuzzy;
	private String version;
	private List<FreeTextSearchElement> hotels;
	private List<FreeTextSearchElement> destinations;
	private List<FreeTextSearchElement> zones;
	private List<FreeTextSearchElement> groupZones;
	private List<FreeTextSearchElement> groupDestinations;


}