/**
 * Autogenerated code by SdkModelGenerator.
 * Do not edit. Any modification on this file will be removed automatically after project build
 *
 */
package com.hotelbeds.hotelcontentapi.auto.messages;

import com.hotelbeds.hotelcontentapi.auto.messages.Location;
import java.util.Map;

import lombok.ToString;
import lombok.NoArgsConstructor;
import lombok.Data;

@ToString
@NoArgsConstructor
@Data
public class FreeTextSearchElement {

	private String code;
	private Map descriptions;
	private Integer weight;
	private Location location;


}