/**
 * Autogenerated code by SdkModelGenerator.
 * Do not edit. Any modification on this file will be removed automatically after project build
 *
 */
package com.hotelbeds.hotelcontentapi.auto.messages;

import com.hotelbeds.hotelcontentapi.util.ContentType;
import java.util.List;
import javax.validation.constraints.NotNull;

import lombok.ToString;
import lombok.NoArgsConstructor;
import lombok.Data;
import lombok.AllArgsConstructor;

@ToString
@NoArgsConstructor
@Data
@AllArgsConstructor
public class FreeTextSearchRQ {

	@NotNull
	private String query;
	@NotNull
	private List<String> languages;
	private ContentType contentType;
	private Integer from;
	private Integer to;
	private Integer nHotels;
	private Integer nZones;
	private Integer nDestinations;
	private String highlightStart;
	private String highlightEnd;
	private Integer fuzzy;
	private Integer nGroupDest;
	private Integer nGroupZones;
	private Integer fuzzyLength;


}