/**
 * Autogenerated code by SdkModelGenerator.
 * Do not edit. Any modification on this file will be removed automatically after project build
 *
 */
package com.hotelbeds.hotelcontentapi.auto.messages;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.hotelbeds.hotelcontentapi.auto.messages.CodedElement;
import com.hotelbeds.hotelcontentapi.auto.messages.HotelRoomFacility;
import com.hotelbeds.hotelcontentapi.auto.messages.HotelRoomStay;
import java.util.List;

import lombok.ToString;
import lombok.NoArgsConstructor;
import lombok.Data;

@JsonInclude(Include.NON_NULL)
@ToString
@NoArgsConstructor
@Data
public class HotelRoom {

	private String roomCode;
	private String description;
	private String roomType;
	private String characteristicCode;
	private CodedElement type;
	private CodedElement characteristic;
	private List<HotelRoomFacility> roomFacilities;
	private List<HotelRoomStay> roomStays;


}