/**
 * Autogenerated code by SdkModelGenerator.
 * Do not edit. Any modification on this file will be removed automatically after project build
 *
 */
package com.hotelbeds.hotelcontentapi.auto.messages;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import java.math.BigDecimal;
import java.util.List;
import javax.validation.constraints.Digits;
import javax.validation.constraints.Min;

import lombok.ToString;
import lombok.NoArgsConstructor;
import lombok.Data;
import lombok.EqualsAndHashCode;

@JsonInclude(Include.NON_NULL)
@ToString
@NoArgsConstructor
@Data
@EqualsAndHashCode(callSuper=false)
public class HotelsRQ extends AbstractGenericContentRequest {

	private String destinationCode;
	private String countryCode;
	@Min(value = 0)
	@Digits(fraction = 1, integer = 1)
	private BigDecimal minTripadvisorRate;
	@Min(value = 0)
	@Digits(fraction = 1, integer = 1)
	private BigDecimal maxTripadvisorRate;
	private List<String> accomodationTypes;


}