/**
 * Autogenerated code by SdkModelGenerator.
 * Do not edit. Any modification on this file will be removed automatically after project build
 *
 */
package com.hotelbeds.hotelcontentapi.auto.messages;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.hotelbeds.hotelcontentapi.auto.convert.json.DateSerializer;
import com.hotelbeds.hotelcontentapi.auto.messages.Content;
import java.time.LocalDate;

import lombok.ToString;
import lombok.NoArgsConstructor;
import lombok.Data;

@JsonInclude(Include.NON_NULL)
@ToString
@NoArgsConstructor
@Data
public class HotelIssue {

	private String issueCode;
	private String issueType;
	private Content description;
	@JsonProperty
	@JsonSerialize(using = DateSerializer.class)
	private LocalDate dateFrom;
	@JsonProperty
	@JsonSerialize(using = DateSerializer.class)
	private LocalDate dateTo;
	private Integer order;
	private Boolean alternative;


}