/**
 * Autogenerated code by SdkModelGenerator.
 * Do not edit. Any modification on this file will be removed automatically after project build
 *
 */
package com.hotelbeds.hotelcontentapi.auto.messages;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.hotelbeds.hotelcontentapi.auto.messages.Accommodation;
import com.hotelbeds.hotelcontentapi.auto.messages.Board;
import com.hotelbeds.hotelcontentapi.auto.messages.Category;
import com.hotelbeds.hotelcontentapi.auto.messages.Chain;
import com.hotelbeds.hotelcontentapi.auto.messages.Content;
import com.hotelbeds.hotelcontentapi.auto.messages.Country;
import com.hotelbeds.hotelcontentapi.auto.messages.Destination;
import com.hotelbeds.hotelcontentapi.auto.messages.GeoLocation;
import com.hotelbeds.hotelcontentapi.auto.messages.HotelFacility;
import com.hotelbeds.hotelcontentapi.auto.messages.HotelIssue;
import com.hotelbeds.hotelcontentapi.auto.messages.HotelPhone;
import com.hotelbeds.hotelcontentapi.auto.messages.HotelPointOfInterest;
import com.hotelbeds.hotelcontentapi.auto.messages.HotelRoom;
import com.hotelbeds.hotelcontentapi.auto.messages.HotelTerminal;
import com.hotelbeds.hotelcontentapi.auto.messages.Image;
import com.hotelbeds.hotelcontentapi.auto.messages.Segment;
import com.hotelbeds.hotelcontentapi.auto.messages.WildCard;
import com.hotelbeds.hotelcontentapi.auto.messages.Zone;
import java.lang.Short;
import java.util.List;

import lombok.ToString;
import lombok.NoArgsConstructor;
import lombok.Data;

@JsonInclude(Include.NON_NULL)
@ToString
@NoArgsConstructor
@Data
public class Hotel {

	private Integer code;
	private Content name;
	private Content description;
	private String countryCode;
	private Country country;
	private String destinationCode;
	private Short zoneCode;
	private Destination destination;
	private Zone zone;
	private GeoLocation coordinates;
	private String categoryCode;
	private Category category;
	private String chainCode;
	private Chain chain;
	private String accommodationTypeCode;
	private Accommodation accommodationType;
	private List<String> boardCodes;
	private List<Board> boards;
	private List<Integer> segmentCodes;
	private List<Segment> segments;
	private Content address;
	private String postalCode;
	private Content city;
	private String email;
	private String license;
	private Integer giataCode;
	private List<HotelPhone> phones;
	private List<HotelRoom> rooms;
	private List<HotelFacility> facilities;
	private List<HotelTerminal> terminals;
	private List<HotelIssue> issues;
	private List<HotelPointOfInterest> interestPoints;
	private List<Image> images;
	private List<WildCard> wildcards;
	private String web;


}