/**
 * Autogenerated code by SdkModelGenerator.
 * Do not edit. Any modification on this file will be removed automatically after project build
 *
 */
package com.hotelbeds.hotelcontentapi.auto.messages;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.hotelbeds.hotelcontentapi.auto.convert.json.DateSerializer;
import com.hotelbeds.hotelcontentapi.auto.convert.json.TimeSerializer;
import com.hotelbeds.hotelcontentapi.auto.messages.Content;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalTime;

import lombok.ToString;
import lombok.NoArgsConstructor;
import lombok.Data;

@JsonInclude(Include.NON_NULL)
@ToString
@NoArgsConstructor
@Data
public class HotelFacility {

	private Integer facilityCode;
	private Integer facilityGroupCode;
	private Content description;
	private Integer order;
	private Boolean indLogic;
	private Boolean indFee;
	private Boolean indYesOrNo;
	private String facilityName;
	private Integer number;
	private Integer distance;
	private Integer ageFrom;
	private Integer ageTo;
	@JsonProperty
	@JsonSerialize(using = DateSerializer.class)
	private LocalDate dateFrom;
	@JsonProperty
	@JsonSerialize(using = DateSerializer.class)
	private LocalDate dateTo;
	@JsonProperty
	@JsonSerialize(using = TimeSerializer.class)
	private LocalTime timeFrom;
	@JsonProperty
	@JsonSerialize(using = TimeSerializer.class)
	private LocalTime timeTo;
	private BigDecimal amount;
	private String currency;
	private String applicationType;


}