/**
 * Autogenerated code by SdkModelGenerator.
 * Do not edit. Any modification on this file will be removed automatically after project build
 *
 */
package com.hotelbeds.hotelcontentapi.auto.messages;


import lombok.ToString;
import lombok.NoArgsConstructor;
import lombok.Data;
import lombok.AllArgsConstructor;

@ToString
@NoArgsConstructor
@Data
@AllArgsConstructor
public class Location {

	private LocationElement zone;
	private LocationElement destination;
	private LocationElement country;


}