/**
 * Autogenerated code by SdkModelGenerator.
 * Do not edit. Any modification on this file will be removed automatically after project build
 *
 */
package com.hotelbeds.hotelcontentapi.auto.messages;

import java.util.Map;

import lombok.ToString;
import lombok.NoArgsConstructor;
import lombok.Data;

@ToString
@NoArgsConstructor
@Data
public class LocationElement {

	private String code;
	private Map descriptions;


}