/**
 * Autogenerated code by SdkModelGenerator.
 * Do not edit. Any modification on this file will be removed automatically after project build
 *
 */
package com.hotelbeds.hotelapimodel.auto.convert.json;

import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.ObjectCodec;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonDeserializer;
import com.fasterxml.jackson.databind.node.TextNode;
import com.hotelbeds.hotelapimodel.auto.util.AssignUtils;

import java.io.IOException;
import java.time.LocalDate;

/**
 *
 * Local copy of {@link com.hotelbeds.hotelapi.hotelapirest.engine.esb.availability.converter.DateDeserializer}
 *
 * Created by joroldan
 */
public class DateDeserializer extends JsonDeserializer<LocalDate> {

    @Override
    public LocalDate deserialize(JsonParser jp, DeserializationContext ctxt) throws IOException {
        ObjectCodec oc = jp.getCodec();
        TextNode node = oc.readTree(jp);
        String dateString = node.textValue();
        return LocalDate.parse(dateString, AssignUtils.REST_FORMATTER);
    }
}
